apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: nginx-volume
        hostPath:
          path: /Users/terrapin/workspace/study/msa-samples/socketio-notification/infra/nginx/default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: nginx-tcp
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
